### ISSUE TITLE
OKD update from 4.10 to 4.11 failed due to permission issue for NetworkManager-dispatcher scripts for VMXNET3 VxLAN offload bug 

### ISSUE THREAD

**Issue by erikmagkekse** [okd-project/okd#1317]
**Describe the bug**
When updating from _4.10.0-0.okd-2022-07-09-073606_ to _4.11.0-0.okd-2022-08-20-022919_, something blocks NetworkManager-dispatcher from executing scripts for workarounds, as example _99-vsphere-disable-tx-udp-tnl_ which is responsible to disable VxLAN offloads for the VMXNET3 issue, if the fix is not applied on all nodes many pods aren't able to communicate correctly which results into a timeout of HTTP requests. We found a similar issue [here](https://github.com/coreos/fedora-coreos-tracker/issues/1156).

So basicly when we upgrade to this version the cluster is not able to continue after restart of the nodes because many pods (like apiservers) arent able to send HTTP request.

However we were able to run the scripts on all machines manually, after that the cluster finished the upgrade to the new version without any new issues. However this is just a workaround, because on a restart we need to rerun the script manually. There are also other things that get ran by the dispatcher which might be required for other things. For me it seems like there is an issue with SELinux after that update with the new Machine Config, sadly i wasn't able to find the issue on my own. Before the update the dispatcher ran normally.

**Version**
4.10.0-0.okd-2022-07-09-073606 -> 4.11.0-0.okd-2022-08-20-022919
IPI on vSphere

**How reproducible**
Create IPI Install on 4.10.0-0.okd-2022-07-09-073606 then update to latest 4.11 version.

**Log bundle**
Log bundle might not be required here, so NetworkManager-dispatcher logs...
<img width="1699" alt="image" src="https://user-images.githubusercontent.com/108617651/186680826-b4536938-894b-4426-871e-87d63a1496f4.png">

**Comment by vrutkovs** [comment]
Please attach (or upload to the public file sharing service) [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data) archive

**Comment by erikmagkekse** [comment]
> Please attach (or upload to the public file sharing service) [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data) archive

Sadly, due to a lot of confidential data we cannot give out the archive.

**Comment by erikmagkekse** [comment]
We found also the same issue for a older OpenShift Version. [https://access.redhat.com/solutions/5896081](https://access.redhat.com/solutions/5896081)

**Comment by jcpowermac** [comment]
@erikmagkekse the upstream kernel has been fixed for this issue for quite a while now. That being said vSphere must also be up-to-date.

- See PR 2766401: https://docs.vmware.com/en/VMware-vSphere/6.7/rn/esxi670-202111001.html
- No KB / documentation for ESXi 7 U3.
- https://bugzilla.redhat.com/show_bug.cgi?id=1941714#c68

**Comment by erikmagkekse** [comment]
> @erikmagkekse the upstream kernel has been fixed for this issue for quite a while now. That being said vSphere must also be up-to-date.
> 
> * See PR 2766401: https://docs.vmware.com/en/VMware-vSphere/6.7/rn/esxi670-202111001.html
> * No KB / documentation for ESXi 7 U3.
> * https://bugzilla.redhat.com/show_bug.cgi?id=1941714#c68

The bug somehow still persists, we have running right now this version.
[https://docs.vmware.com/en/VMware-vSphere/6.7/rn/esxi670-202201001.html](https://docs.vmware.com/en/VMware-vSphere/6.7/rn/esxi670-202201001.html)

**Comment by jcpowermac** [comment]
@erikmagkekse well unfortunately without any logs kinda hard to troubleshoot. If that is the case you should open a SR with VMware as they would support the vmxnet3 linxu driver and ESXi. 

I have tested extensively with OKD 4.10 and vSphere 7U3 disabling the mitgations - I no longer experienced the issue.

**Comment by erikmagkekse** [comment]
> @erikmagkekse well unfortunately without any logs kinda hard to troubleshoot. If that is the case you should open a SR with VMware as they would support the vmxnet3 linxu driver and ESXi.
> 
> We should figure out how wide spread the dispatch scripts are failing.
> 
> I have tested extensively with OKD 4.10 and vSphere 7U3 disabling the mitgations - I no longer experienced the issue.

I will try to create a new vanilla cluster tomorrow, there i can send them some logs :) That should work out then.

**Comment by vrutkovs** [comment]
I can't imagine how can a faulty driver change file permissions and kubelet can't start. Its possible a bad SELinux rules were installed though (similar to #1285)

**Comment by erikmagkekse** [comment]
> I can't imagine how can a faulty driver change file permissions and kubelet can't start. Its possible a bad SELinux rules were installed though (similar to #1285)

I also do not think that causes that issues, but for some reason the fixes that the NetworkManager loads aren't loading anymore because of permission issues. I think on the update something changed on SELinix permissions.

**Comment by erikmagkekse** [comment]
I am deploying right now a new cluster to reproduce this issue, however i found out that on upgrade from 4.10 to 4.11 we got also Fedora CoreOS updated to 36, i think we are affected from [this bug](https://github.com/coreos/fedora-coreos-tracker/issues/1156) that got fixed in newer versions of Fedora CoreOS.

Which version is 4.11 OKD of Fedora CoreOS using?

**Comment by erikmagkekse** [comment]
36.202208191044 is running, so normaly the bug should be fixed, but doesnt seem like it.

**Comment by erikmagkekse** [comment]
Here the [must-gather.zip](https://github.com/okd-project/okd/files/9432636/must-gather.zip).

It took a very long time to generate that because the cluster has a lot of timeouts due to connectivity issues. I really hope we find a solution.

**Comment by erikmagkekse** [comment]
Any ideas?

**Comment by hy-ntyni** [comment]
We're also affected by this. The mitigation in `/etc/NetworkManager/dispatcher.d/99-vsphere-disable-tx-udp-tnl` stopped working when we updated to OKD 4.11, and the VXLAN overlay network started misbehaving. Manually running the ethtool commands fixes it until next boot. We're at version 4.11.0-0.okd-2022-08-20-022919.

Logs show NetworkManager-dispatcher failing to open `/etc/NetworkManager/dispatcher.d` due to SELinux policies, identically with the earlier screenshot in this issue.

**Comment by erikmagkekse** [comment]
> We're also affected by this. The mitigation in `/etc/NetworkManager/dispatcher.d/99-vsphere-disable-tx-udp-tnl` stopped working when we updated to OKD 4.11, and the VXLAN overlay network started misbehaving. Manually running the ethtool commands fixes it until next boot. We're at version 4.11.0-0.okd-2022-08-20-022919.
> 
> Logs show NetworkManager-dispatcher failing to open `/etc/NetworkManager/dispatcher.d` due to SELinux policies, identically with the earlier screenshot in this issue.

Oh sorry to hear that! At least we are not the only one who had that issue.

I hope that someone will find an fix for that at least for the next 4.11 update.

**Comment by hy-ntyni** [comment]
> I can't imagine how can a faulty driver change file permissions and kubelet can't start. Its possible a bad SELinux rules were installed though (similar to #1285)

Indeed the SELinux context labels in installed files are not up to date wrt. the policy, as shown by for instance `fixfiles -R NetworkManager check`:

```
Would relabel /etc/NetworkManager/dispatcher.d from system_u:object_r:NetworkManager_initrc_exec_t:s0 to system_u:object_r:NetworkManager_dispatcher_script_t:s0
Would relabel /etc/NetworkManager/dispatcher.d/pre-up.d from system_u:object_r:NetworkManager_initrc_exec_t:s0 to system_u:object_r:NetworkManager_dispatcher_script_t:s0
Would relabel /etc/NetworkManager/dispatcher.d/pre-up.d/10-ofport-request.sh from system_u:object_r:NetworkManager_initrc_exec_t:s0 to system_u:object_r:NetworkManager_dispatcher_script_t:s0
Would relabel /etc/NetworkManager/dispatcher.d/99-vsphere-disable-tx-udp-tnl from system_u:object_r:NetworkManager_initrc_exec_t:s0 to system_u:object_r:NetworkManager_dispatcher_script_t:s0
Would relabel /etc/NetworkManager/dispatcher.d/30-resolv-prepender from system_u:object_r:NetworkManager_initrc_exec_t:s0 to system_u:object_r:NetworkManager_dispatcher_script_t:s0
Would relabel /etc/NetworkManager/dispatcher.d from system_u:object_r:NetworkManager_initrc_exec_t:s0 to system_u:object_r:NetworkManager_dispatcher_script_t:s0
Would relabel /etc/NetworkManager/dispatcher.d/pre-up.d from system_u:object_r:NetworkManager_initrc_exec_t:s0 to system_u:object_r:NetworkManager_dispatcher_script_t:s0
Would relabel /etc/NetworkManager/dispatcher.d/pre-up.d/10-ofport-request.sh from system_u:object_r:NetworkManager_initrc_exec_t:s0 to system_u:object_r:NetworkManager_dispatcher_script_t:s0
Would relabel /etc/NetworkManager/dispatcher.d/99-vsphere-disable-tx-udp-tnl from system_u:object_r:NetworkManager_initrc_exec_t:s0 to system_u:object_r:NetworkManager_dispatcher_script_t:s0
Would relabel /etc/NetworkManager/dispatcher.d/30-resolv-prepender from system_u:object_r:NetworkManager_initrc_exec_t:s0 to system_u:object_r:NetworkManager_dispatcher_script_t:s0
Would relabel /etc/NetworkManager/dispatcher.d/pre-up.d from system_u:object_r:NetworkManager_initrc_exec_t:s0 to system_u:object_r:NetworkManager_dispatcher_script_t:s0
Would relabel /etc/NetworkManager/dispatcher.d/pre-up.d/10-ofport-request.sh from system_u:object_r:NetworkManager_initrc_exec_t:s0 to system_u:object_r:NetworkManager_dispatcher_script_t:s0
```

I haven't been able to determine the cause yet. We don't have any local modifications to SELinux policies and haven't fiddled anywhere around them before this AFAIK. The cluster has a longish upgrade history from at least 4.5.

```
# ostree admin config-diff | grep selinux
M    selinux/targeted/active/commit_num
A    selinux/targeted/semanage.read.LOCK
A    selinux/targeted/semanage.trans.LOCK
```

**Comment by travier** [comment]
Short term workaround: Run `sudo semodule -B` on all nodes.

**Comment by hy-ntyni** [comment]
> Short term workaround: Run `sudo semodule -B` on all nodes.

That's really short term as the relabeling won't persist over a reboot afaics.

**Comment by erikmagkekse** [comment]
I have created a quick workaround via a systemd unit that will run restorecon before network.target starts.
This will ensure on every boot that the NetworkManager-dispatcher can run the required fixes/workarounds. It also works with new nodes that get deployed like with a IPI installation that we use.

The workaround worked fine for our master and worker nodes. The Config down below is configured only for worker, we applied the same thing again with different name and label for master nodes.

<img width="1107" alt="Screenshot 2022-09-13 163158" src="https://user-images.githubusercontent.com/108617651/189929737-1fef6a87-86aa-443f-8726-f85a0ea91928.png">

[OKD_issue_1317_workaround.txt](https://github.com/okd-project/okd/files/9558275/OKD_issue_1317_workaround.txt)

**Comment by travier** [comment]
`semodule -B` rebuilds the SELinux policy and reloads it, which should resolve issue with old policies.

If the labels or not correct on configuration files, then you only need to reset them once, they won't be changed again.

**Comment by erikmagkekse** [comment]
> `semodule -B` rebuilds the SELinux policy and reloads it, which should resolve issue with old policies.
> 
> If the labels or not correct on configuration files (`/etc`), then you only need to reset them once, they won't be changed again.

Sure, but not on new deployed nodes, we have running Autoscalers that will deploy automaticly new nodes in vSphere. That is the issue for us.

**Comment by travier** [comment]
Your MachineConfig looks like a good workaround. I'm wondering why we're only seeing that here and not elsewhere.

**Comment by LorbusChris** [comment]
Looks like we might need to port https://github.com/openshift/os/pull/962 to okd-machine-os as well in order to fix this. Vanilla FCOS might be affected too.

**Comment by klzsysy** [comment]
Based on the above discussion, merge @erikmagkekse @travier fix  patch,  from 4.10.0-0.okd-2022-07-09-073606 upgrade to 4.11.0-0.okd-2022-07-29-154152 is successful

```yaml
oc create -f - <<'EOF'
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: networkmanager-selinux-bug-workaround-v1-master
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.2.0
    systemd:
      units:
        - contents: >
            [Unit]
            Description=NetworkManager-dispatcher SELinux fix - Workaround for https://github.com/okd-project/okd/issues/1317
            [Service]
            Restart=no
            Type=oneshot
            ExecStart=/bin/bash -c 'restorecon -rv /etc/NetworkManager/dispatcher.d/;semodule -B'
            [Install]
            WantedBy=network.target
          enabled: true
          name: networkmanager-selinux-workaround.service
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: networkmanager-selinux-bug-workaround-v1-worker
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.2.0
    systemd:
      units:
        - contents: >
            [Unit]
            Description=NetworkManager-dispatcher SELinux fix - Workaround for https://github.com/okd-project/okd/issues/1317
            [Service]
            Restart=no
            Type=oneshot
            ExecStart=/bin/bash -c 'restorecon -rv /etc/NetworkManager/dispatcher.d/;semodule -B'
            [Install]
            WantedBy=network.target
          enabled: true
          name: networkmanager-selinux-workaround.service
EOF

# restart machine config daemon
oc -n openshift-machine-config-operator delete pod --all
# Then check that the master node machine-config-daemon pod log 
```

**Comment by erikmagkekse** [comment]
I will close this issue because it got fixed by https://github.com/openshift/okd-machine-os/pull/451
