### ISSUE TITLE
openshift-servicemesh (istio-maistra operator) stops working with upgrade to 4.11.0-0.okd-2022-12-02-145640 (SELinux)

### ISSUE THREAD

**Issue by dan1el-k** [okd-project/okd#1450]
**Describe the bug**
With the upgrade to OKD version 4.11.0-0.okd-2022-12-02-145640, the istio sidecar proxy weren't able to boot up anymore.
We tested it with openshift-servicemesh version 2.1 and 2.3. 2.3 gaves some more sophisticated error message (see below)

Obviously some latest change on SELinux cause the issue. In the audit logs we can find some blocked calls in this regarding, and 
disabling SELinux fixes the problem.

**Version**
release: 4.11.0-0.okd-2022-12-02-145640 
IPI on AWS air gapped

**How reproducible**
100% reproducible.
1. Update OKD to version: 4.11.0-0.okd-2022-12-02-145640 
2. install/reinstall openshift-servicemesh (maistra-operator) version 2.3 
3. deploy an pod in a namespace which is ServiceMesh enabled and pod label "sidecar.istio.io/inject: 'true'" 

**Log bundle**

Error Message
`
(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox <pod-name> : error adding pod <pod-name> to CNI network "multus-cni-network": plugin type="multus" name="multus-cni-network" failed (add): [<pod-name>/f50bf89f-df6b-4fae-9223-67a491cc106a:v2-3-istio-cni]: error adding container to network "v2-3-istio-cni": netplugin failed: "{\"level\":\"info\",\"time\":\"2022-12-21T22:19:17.542287Z\",\"msg\":\"istio-cni cmdAdd with k8s args: {CommonArgs:{IgnoreUnknown:true} IP:<nil> K8S_POD_NAME:<pod-name> K8S_POD_NAMESPACE:dev01-ecds K8S_POD_INFRA_CONTAINER_ID:8036aaa3a1457ce57c248bfdf4e061e7bdbafdca1b0ed682eb25bef50dfe1250}\"}\n{\"level\":\"info\",\"time\":\"2022-12-21T22:19:17.556571Z\",\"msg\":\"============= Start iptables configuration for <pod-name> =============\"}\n{\"level\":\"info\",\"time\":\"2022-12-21T22:19:17.556750Z\",\"msg\":\"Istio iptables environment:\\nENVOY_PORT=\\nINBOUND_CAPTURE_PORT=\\nISTIO_INBOUND_INTERCEPTION_MODE=\\nISTIO_INBOUND_TPROXY_ROUTE_TABLE=\\nISTIO_INBOUND_PORTS=\\nISTIO_OUTBOUND_PORTS=\\nISTIO_LOCAL_EXCLUDE_PORTS=\\nISTIO_EXCLUDE_INTERFACES=\\nISTIO_SERVICE_CIDR=\\nISTIO_SERVICE_EXCLUDE_CIDR=\\nISTIO_META_DNS_CAPTURE=\\nINVALID_DROP=\\n\"}\n{\"level\":\"info\",\"time\":\"2022-12-21T22:19:17.556798Z\",\"msg\":\"Istio iptables variables:\\nPROXY_PORT=15001\\nPROXY_INBOUND_CAPTURE_PORT=15006\\nPROXY_TUNNEL_PORT=15008\\nPROXY_UID=1000970001\\nPROXY_GID=0\\nINBOUND_INTERCEPTION_MODE=REDIRECT\\nINBOUND_TPROXY_MARK=1337\\nINBOUND_TPROXY_ROUTE_TABLE=133\\nINBOUND_PORTS_INCLUDE=*\\nINBOUND_PORTS_EXCLUDE=15090,15021,15020\\nOUTBOUND_OWNER_GROUPS_INCLUDE=*\\nOUTBOUND_OWNER_GROUPS_EXCLUDE=\\nOUTBOUND_IP_RANGES_INCLUDE=*\\nOUTBOUND_IP_RANGES_EXCLUDE=\\nOUTBOUND_PORTS_INCLUDE=\\nOUTBOUND_PORTS_EXCLUDE=15020\\nKUBE_VIRT_INTERFACES=\\nENABLE_INBOUND_IPV6=false\\nDNS_CAPTURE=true\\nDROP_INVALID=false\\nCAPTURE_ALL_DNS=true\\nDNS_SERVERS=[],[]\\nOUTPUT_PATH=\\nNETWORK_NAMESPACE=/var/run/netns/e39408ce-c075-4872-99b7-068fd4b98ea0\\nCNI_MODE=true\\nEXCLUDE_INTERFACES=\\n\"}\n{\"level\":\"info\",\"time\":\"2022-12-21T22:19:17.556875Z\",\"msg\":\"Writing following contents to rules file: /tmp/iptables-rules-1671661157556852367.txt2715146301\\n* nat\\n-N ISTIO_INBOUND\\n-N ISTIO_REDIRECT\\n-N ISTIO_IN_REDIRECT\\n-N ISTIO_OUTPUT\\n-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN\\n-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001\\n-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006\\n-A PREROUTING -p tcp -j ISTIO_INBOUND\\n-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN\\n-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN\\n-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN\\n-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT\\n-A OUTPUT -p tcp -j ISTIO_OUTPUT\\n-A ISTIO_OUTPUT -p tcp --dport 15020 -j RETURN\\n-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN\\n-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -p tcp ! --dport 53 -m owner --uid-owner 1000970001 -j ISTIO_IN_REDIRECT\\n-A ISTIO_OUTPUT -o lo -p tcp ! --dport 53 -m owner ! --uid-owner 1000970001 -j RETURN\\n-A ISTIO_OUTPUT -m owner --uid-owner 1000970001 -j RETURN\\n-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 0 -j ISTIO_IN_REDIRECT\\n-A ISTIO_OUTPUT -o lo -p tcp ! --dport 53 -m owner ! --gid-owner 0 -j RETURN\\n-A ISTIO_OUTPUT -m owner --gid-owner 0 -j RETURN\\n-A ISTIO_OUTPUT -p tcp --dport 53 -j REDIRECT --to-ports 15053\\n-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN\\n-A ISTIO_OUTPUT -j ISTIO_REDIRECT\\n-A OUTPUT -p udp --dport 53 -m owner --uid-owner 1000970001 -j RETURN\\n-A OUTPUT -p udp --dport 53 -m owner --gid-owner 0 -j RETURN\\n-A OUTPUT -p udp --dport 53 -j REDIRECT --to-port 15053\\nCOMMIT\\n* raw\\n-A OUTPUT -p udp --dport 53 -m owner --uid-owner 1000970001 -j CT --zone 1\\n-A OUTPUT -p udp --sport 15053 -m owner --uid-owner 1000970001 -j CT --zone 2\\n-A OUTPUT -p udp --dport 53 -m owner --gid-owner 0 -j CT --zone 1\\n-A OUTPUT -p udp --sport 15053 -m owner --gid-owner 0 -j CT --zone 2\\n-A OUTPUT -p udp --dport 53 -j CT --zone 2\\n-A PREROUTING -p udp --sport 53 -j CT --zone 1\\nCOMMIT\"}\n{\"level\":\"info\",\"time\":\"2022-12-21T22:19:17.556910Z\",\"msg\":\"Running command: nsenter --net=/var/run/netns/e39408ce-c075-4872-99b7-068fd4b98ea0 -- iptables-restore --noflush /tmp/iptables-rules-1671661157556852367.txt2715146301\"}\n{\"level\":\"error\",\"time\":\"2022-12-21T22:19:17.558954Z\",\"msg\":\"Command error output: xtables other problem: Permission denied\"}\n{\"level\":\"error\",\"time\":\"2022-12-21T22:19:17.558970Z\",\"msg\":\"Failed to execute: iptables-restore --noflush /tmp/iptables-rules-1671661157556852367.txt2715146301, exit status 1\"}\n"
`

**Workaround**

As a workaround to make it work again, you can enable SELINUX to permissive mode on the OKD nodes. This can be done by applying following machineconfig:

```yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: cortex-worker-kernelarg-selinuxpermissive
spec:
  config:
    ignition:
      version: 3.2.0
  # https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html/nodes/working-with-nodes#nodes-nodes-kernel-arguments_nodes-nodes-jobs
  kernelArguments:
    - enforcing=0
```

**Comment by dan1el-k** [comment]
This issues seems to be connected:
- https://github.com/okd-project/okd/issues/1438
- https://github.com/istio/istio/issues/42485

**Comment by alishchytovych** [comment]
Same here, issue is reproducible in Maistra 2.2, and the latest Istio as well.
Have to postpone updates to the version 2022-12-02.

**Comment by vrutkovs** [comment]
Dupe of #1438

**Comment by vrutkovs** [comment]
Reopening as it also needs a custom SELinux rule, but a different one

**Comment by fortinj66** [comment]
Is there a target timeframe for the SELinux rule?  I can verify that this is also an issue in greenfield OKD 4.12 installs

**Comment by fortinj66** [comment]
Looks like istio is still broken on the latest release 4.12.0-0.okd-2023-04-01-051724

**Comment by alishchytovych** [comment]
The good news is that is should be fixed in istio. The existing fix hasn't been included into 1.17.2, so perhaps in 1.18

**Comment by llomgui** [comment]
> What fix are you referencing? I was under the impression this was an selinux issue with fcos.

Should be fixed in 2.3.3 : https://github.com/istio/istio/issues/42485#issuecomment-1494002858

**Comment by fortinj66** [comment]
I can verify that Istio 1.18 fixes the issue with one caveat...  Upgrade from 1.17 to 1.18 did not fix it.  I had to uninstall Istio 1.17 and install Istio 1.18...

**Comment by alishchytovych** [comment]
> I can verify that Istio 1.18 fixes the issue with one caveat... Upgrade from 1.17 to 1.18 did not fix it. I had to uninstall Istio 1.17 and install Istio 1.18...
> 
> This is on an OKD 4.13 cluster...

Have you installed 1.17 via helm or istioctl?

**Comment by dan1el-k** [comment]
the issue is also fixed with upgrading to ServiceMesh operator version 2.4.1 (containing Istio: 1.16.5) and tested on OKD 4.11., 4.12 and 4.13 clusters.
So I think this can be closed
