### ISSUE TITLE
Network metrics are not displayed in the console for most pods.

### ISSUE THREAD

**Issue by ibotty** [okd-project/okd#1637]
**Describe the bug**

Network metrics are not displayed in the console for **most** pods.

The only pods that have network metrics are pods in `rook-ceph` and the pod in the `openshift-cluster-samples-operator` namespace.

**Version**
4.13.0-0.okd-2023-06-04-080300 on bare-metal UPI hosts with `kubernetes-ovn`.

**Further debugging info**

This is most likely due to cadvisor not including the metrics like `container_network_receive_bytes_total` for most pods.

```
> for node in $(oc get node --no-headers | cut -f1 -d\ |xargs); do echo $node;oc get --raw /api/v1/nodes/$node/proxy/metrics/cadvisor |grep container_network_receive_bytes_total|grep -v rook-ceph; done
# HELP container_network_receive_bytes_total Cumulative count of bytes received
# TYPE container_network_receive_bytes_total counter
container_network_receive_bytes_total{container="",id="/",image="",interface="006902fb24437d6",name="",namespace="",pod=""} 4.955782943e+09 1687243871978
container_network_receive_bytes_total{container="",id="/",image="",interface="0810faaaacf11ee",name="",namespace="",pod=""} 8.1591756e+07 1687243871978
container_network_receive_bytes_total{container="",id="/",image="",interface="0bcbedf02e07089",name="",namespace="",pod=""} 19864 1687243871978
container_network_receive_bytes_total{container="",id="/",image="",interface="13870187b02bc5d",name="",namespace="",pod=""} 9.5674860908e+10 1687243871978
container_network_receive_bytes_total{container="",id="/",image="",interface="13f5e2133620f81",name="",namespace="",pod=""} 19864 1687243871978
container_network_receive_bytes_total{container="",id="/",image="",interface="1e993a614b763e5",name="",namespace="",pod=""} 3.99420707e+08 1687243871978
container_network_receive_bytes_total{container="",id="/",image="",interface="2936e6c3dbc52d5",name="",namespace="",pod=""} 3.8075434e+07 1687243871978
container_network_receive_bytes_total{container="",id="/",image="",interface="2a063fc7718ae52",name="",namespace="",pod=""} 19864 1687243871978
container_network_receive_bytes_total{container="",id="/",image="",interface="485a42eb75475ee",name="",namespace="",pod=""} 9.4043092e+08 1687243871978
container_network_receive_bytes_total{container="",id="/",image="",interface="5f5f1da0029f2af",name="",namespace="",pod=""} 4.5244313e+08 1687243871978
container_network_receive_bytes_total{container="",id="/",image="",interface="98bc2ff64c758b8",name="",namespace="",pod=""} 7.46250017e+08 1687243871978
container_network_receive_bytes_total{container="",id="/",image="",interface="a9fd96197e65d37",name="",namespace="",pod=""} 2.93021457e+08 1687243871978
container_network_receive_bytes_total{container="",id="/",image="",interface="ba02915eae5f56f",name="",namespace="",pod=""} 19864 1687243871978
container_network_receive_bytes_total{container="",id="/",image="",interface="br-ex",name="",namespace="",pod=""} 1.10675192354e+12 1687243871978
container_network_receive_bytes_total{container="",id="/",image="",interface="br-int",name="",namespace="",pod=""} 0 1687243871978
container_network_receive_bytes_total{container="",id="/",image="",interface="e2c2fceeefb6a3c",name="",namespace="",pod=""} 4.063803954e+09 1687243871978
container_network_receive_bytes_total{container="",id="/",image="",interface="e79d8e9c8291bca",name="",namespace="",pod=""} 4.141131368e+09 1687243871978
container_network_receive_bytes_total{container="",id="/",image="",interface="ebd8dd438a78485",name="",namespace="",pod=""} 1.9304550074e+10 1687243871978
container_network_receive_bytes_total{container="",id="/",image="",interface="enp41s0",name="",namespace="",pod=""} 1.464266598749e+12 1687243871978
container_network_receive_bytes_total{container="",id="/",image="",interface="genev_sys_6081",name="",namespace="",pod=""} 2.93736703256e+11 1687243871978
container_network_receive_bytes_total{container="",id="/",image="",interface="ovn-k8s-mp0",name="",namespace="",pod=""} 2.4336215519e+10 1687243871978
container_network_receive_bytes_total{container="",id="/",image="",interface="ovs-system",name="",namespace="",pod=""} 0 1687243871978
control2.cluster.zebralution.it
# HELP container_network_receive_bytes_total Cumulative count of bytes received
# TYPE container_network_receive_bytes_total counter
container_network_receive_bytes_total{container="",id="/",image="",interface="085f3b146e0f65c",name="",namespace="",pod=""} 4.74915002e+08 1687243869265
container_network_receive_bytes_total{container="",id="/",image="",interface="0a03717d555d19b",name="",namespace="",pod=""} 19976 1687243869265
container_network_receive_bytes_total{container="",id="/",image="",interface="0d59097dd4d8a4c",name="",namespace="",pod=""} 8.84173605e+08 1687243869265
container_network_receive_bytes_total{container="",id="/",image="",interface="0db6177bc8212f0",name="",namespace="",pod=""} 4.939326616e+09 1687243869265
container_network_receive_bytes_total{container="",id="/",image="",interface="150fb51abbfd7f6",name="",namespace="",pod=""} 1.98240086e+08 1687243869265
container_network_receive_bytes_total{container="",id="/",image="",interface="1bf58f3e1857467",name="",namespace="",pod=""} 3.74712259e+08 1687243869265
container_network_receive_bytes_total{container="",id="/",image="",interface="1f275765693dacc",name="",namespace="",pod=""} 7.04302693e+08 1687243869265
[...]
container_network_receive_bytes_total{container="POD",id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podbc87710e_046e_4e35_9b32_e9cd4646bd7b.slice/crio-fe50c35dc6746b63042910ce00e828db885e99f54b60
48c83ea279d7742e728f.scope",image="",interface="eth0",name="k8s_POD_cluster-samples-operator-7f8f754fb6-5lm4s_openshift-cluster-samples-operator_bc87710e-046e-4e35-9b32-e9cd4646bd7b_0",namespace="openshift-cluster
-samples-operator",pod="cluster-samples-operator-7f8f754fb6-5lm4s"} 1.14311955e+08 168724386863
[...]
```

**Log bundle**
https://send.vis.ee/download/70f763dc15dbe353/#ZkbFQ9pIObnHHEJ2kbkZ3g

**Comment by ibotty** [comment]
I don't think so.  AFAICT the bug report is only for restarted pods.  I have many pods which don't have any network metrics but no restarts.

**Comment by vrutkovs** [comment]
[KCS](https://access.redhat.com/solutions/7012770) says its not just for restarts, it can happen itself after some time.

I'll be preparing a new OKD stable soon - I wonder if you could try a new nightly to confirm this fix resolves it?

**Comment by ibotty** [comment]
I can try a nightly, yes.

**Comment by ibotty** [comment]
This also happens with 4.13.0-0.okd-2023-06-24-145750

**Comment by vrutkovs** [comment]
Checked 4.13.0-0.okd-2023-07-09-062029 - and seeing this too. Seems its related to CRI-O - https://issues.redhat.com/browse/OCPBUGS-14589 mentions https://github.com/cri-o/cri-o/pull/6875, which went in OCP but OKD is using official releases so this wasn't patched yet.

Confirming that its fixed in 4.14 (it should be using cri-o from the latest commit).

I'm going to ask for a new CRIO v1.26.4 released to have it land in 4.13 nightly (a custom OS with this patch could also be built to have it fixed now)

**Comment by ibotty** [comment]
I can attest that it's fixed in 4.14.0-0.okd-2023-10-28-073550.  Closing.

**Comment by lftgl** [comment]
I am using okd version: 4.14.0-0.okd-2024-01-06-084517 and still have the same problems with the network metrics.

I'm not quite sure when it started, but since the last update I no longer have container_network_* metrics.

I know the metrics are there, but the labels pod, namespace, container are all empty.

Anyone else with the same problems on okd 4.14.0-x ?
